/* ===== AI AND ACCOUNTABILITY — MAIN SCRIPT ===== */

(function () {
  'use strict';

  const TOTAL_SECTIONS = 6;
  let currentSection = 0;

  // Quiz state
  let quizScore = 0;
  let currentQuestion = 1;
  const TOTAL_QUESTIONS = 5;

  const feedbackMessages = {
    1: {
      correct: '✓ Correct! AI models predict statistically likely text — they have no mechanism to verify truth. That\'s why confident-sounding false information is called a "hallucination."',
      wrong: '✗ Not quite. Hallucination refers to AI generating false information that sounds confident and plausible — it\'s a structural feature of how language models work, not just an occasional glitch.'
    },
    2: {
      correct: '✓ Correct! Lawyer Steven Schwartz submitted six fake cases generated by ChatGPT and was fined $5,000. This became the first major public case involving AI hallucination in a professional setting.',
      wrong: '✗ Not quite. In Mata v. Avianca, lawyer Steven Schwartz submitted AI-generated fake legal citations to a federal court without verifying them, and was fined and sanctioned.'
    },
    3: {
      correct: '✓ Correct! AI companies currently shield themselves through liability disclaimers in their terms of service. Users and professionals bear the legal exposure under current US law.',
      wrong: '✗ Not quite. Under current US law, AI companies have the most legal protection — they use liability disclaimers in their terms of service to avoid responsibility for harms.'
    },
    4: {
      correct: '✓ Correct! The Shared Regulatory Framework is grounded in the principle that responsibility should be proportional to one\'s role, expertise, and ability to prevent harm.',
      wrong: '✗ Not quite. The Shared Regulatory Framework rests on the idea that responsibility should match a person\'s ability and role — experts bear more responsibility than laypeople.'
    },
    5: {
      correct: '✓ Correct! General end-users are described as the least protected group under current law. They often lack the expertise to verify AI outputs and have the fewest legal options when harmed.',
      wrong: '✗ Not quite. General end-users — everyday people using AI for health, legal, or personal questions — are the least protected group under current law.'
    }
  };

  // ===== DOM ELEMENTS =====
  const sections = Array.from(document.querySelectorAll('.page-section'));
  const navLinks = Array.from(document.querySelectorAll('.nav-section-link'));
  const progressFill = document.getElementById('progress-fill');
  const progressLabel = document.getElementById('progress-label');
  const progressLabelMobile = document.getElementById('progress-label-mobile');
  const progressContainer = document.getElementById('progress-root');
  const startBtn = document.getElementById('start-btn');
  const finishBtn = document.getElementById('finish-btn');
  const retakeBtn = document.getElementById('retake-btn');

  // ===== SECTION NAVIGATION =====

  function goToSection(index) {
    if (index < 0 || index >= TOTAL_SECTIONS) return;

    // Hide current
    sections[currentSection].classList.remove('active');
    sections[currentSection].setAttribute('hidden', '');

    // Show new
    currentSection = index;
    sections[currentSection].removeAttribute('hidden');
    sections[currentSection].classList.add('active');

    updateProgress();
    updateNavLinks();
    updateNavButtons();

    // Scroll to top
    window.scrollTo({ top: 0, behavior: 'smooth' });

    // Announce section change to screen readers
    const heading = sections[currentSection].querySelector('h1, h2');
    if (heading) heading.focus({ preventScroll: true });
  }

  function updateProgress() {
    const percent = ((currentSection + 1) / TOTAL_SECTIONS) * 100;
    if (progressFill) progressFill.style.width = percent + '%';
    const labelText = `Section ${currentSection + 1} of ${TOTAL_SECTIONS}`;
    if (progressLabel) progressLabel.textContent = labelText;
    if (progressLabelMobile) progressLabelMobile.textContent = labelText;
    if (progressContainer) {
      progressContainer.setAttribute('aria-valuenow', currentSection + 1);
    }
  }

  function updateNavLinks() {
    navLinks.forEach((link, i) => {
      link.classList.toggle('active', i === currentSection);
      link.setAttribute('aria-current', i === currentSection ? 'page' : 'false');
    });
  }

  function updateNavButtons() {
    const section = sections[currentSection];
    const prevBtns = section.querySelectorAll('.btn-prev');
    const nextBtns = section.querySelectorAll('.btn-next');

    prevBtns.forEach(btn => {
      btn.disabled = currentSection === 0;
    });

    nextBtns.forEach(btn => {
      btn.disabled = currentSection === TOTAL_SECTIONS - 1;
    });
  }

  // ===== EVENT LISTENERS =====

  // Next / Prev buttons (delegated)
  document.addEventListener('click', function (e) {
    if (e.target.closest('.btn-next')) {
      goToSection(currentSection + 1);
    } else if (e.target.closest('.btn-prev')) {
      goToSection(currentSection - 1);
    }
  });

  // Start button on hero
  if (startBtn) {
    startBtn.addEventListener('click', function (e) {
      e.preventDefault();
      goToSection(currentSection + 1);
    });
  }

  // Nav links
  navLinks.forEach((link, i) => {
    link.addEventListener('click', function (e) {
      e.preventDefault();
      goToSection(i);
    });
  });

  // Finish button
  if (finishBtn) {
    finishBtn.addEventListener('click', function () {
      this.innerHTML = 'Thanks for reading! ✓';
      this.disabled = true;
    });
  }

  // ===== QUIZ LOGIC =====

  function getQuestionEl(num) {
    return document.getElementById('q' + num);
  }

  function showNextQuestion() {
    const current = getQuestionEl(currentQuestion);
    if (current) {
      current.setAttribute('hidden', '');
      current.classList.remove('active');
    }

    if (currentQuestion >= TOTAL_QUESTIONS) {
      showResults();
      return;
    }

    currentQuestion++;
    const next = getQuestionEl(currentQuestion);
    if (next) {
      next.removeAttribute('hidden');
      next.classList.add('active');
    }
  }

  function showResults() {
    const resultsEl = document.getElementById('quiz-results');
    resultsEl.removeAttribute('hidden');

    const scoreDisplay = document.getElementById('score-display');
    scoreDisplay.textContent = quizScore;

    const msg = document.getElementById('results-message');
    if (quizScore === 5) {
      msg.textContent = 'Perfect score! You have a strong grasp of AI accountability issues.';
    } else if (quizScore >= 3) {
      msg.textContent = 'Good work! Review the sections you found tricky and revisit the concepts.';
    } else {
      msg.textContent = 'Keep going — consider rereading the sections on hallucination and liability to reinforce the key ideas.';
    }

    // Enable finish button
    if (finishBtn) finishBtn.disabled = false;
  }

  // Handle quiz option clicks (delegated)
  document.addEventListener('click', function (e) {
    const option = e.target.closest('.quiz-option');
    if (!option) return;

    const questionEl = option.closest('.quiz-question');
    if (!questionEl) return;

    const questionNum = parseInt(questionEl.dataset.question, 10);
    const isCorrect = option.dataset.correct === 'true';
    const feedbackEl = questionEl.querySelector('.quiz-feedback');

    // Disable all options in this question
    const allOptions = questionEl.querySelectorAll('.quiz-option');
    allOptions.forEach(opt => {
      opt.disabled = true;
      if (opt.dataset.correct === 'true') {
        opt.classList.add('correct');
      } else if (opt === option && !isCorrect) {
        opt.classList.add('wrong');
      }
    });

    // Show feedback
    const msgs = feedbackMessages[questionNum];
    feedbackEl.textContent = '';
    const msgSpan = document.createElement('span');
    msgSpan.textContent = isCorrect ? msgs.correct : msgs.wrong;
    feedbackEl.appendChild(msgSpan);
    feedbackEl.className = 'quiz-feedback show ' + (isCorrect ? 'correct-fb' : 'wrong-fb');

    // Add next button
    const nextLabel = currentQuestion < TOTAL_QUESTIONS ? 'Next Question →' : 'See Results →';
    const nextBtn = document.createElement('button');
    nextBtn.type = 'button';
    nextBtn.className = 'btn quiz-next next-q-btn';
    nextBtn.textContent = nextLabel;
    nextBtn.setAttribute('aria-label', nextLabel);
    feedbackEl.appendChild(document.createElement('br'));
    feedbackEl.appendChild(nextBtn);

    nextBtn.addEventListener('click', function () {
      showNextQuestion();
    });

    if (isCorrect) quizScore++;
  });

  // Retake quiz
  if (retakeBtn) {
    retakeBtn.addEventListener('click', function () {
      quizScore = 0;
      currentQuestion = 1;

      // Hide results
      document.getElementById('quiz-results').setAttribute('hidden', '');

      // Reset all questions
      for (let i = 1; i <= TOTAL_QUESTIONS; i++) {
        const qEl = getQuestionEl(i);
        if (!qEl) continue;

        // Re-enable options and remove state classes
        qEl.querySelectorAll('.quiz-option').forEach(opt => {
          opt.disabled = false;
          opt.classList.remove('correct', 'wrong');
        });

        // Clear feedback
        const feedback = qEl.querySelector('.quiz-feedback');
        feedback.innerHTML = '';
        feedback.className = 'quiz-feedback';

        // Hide all except Q1
        if (i === 1) {
          qEl.removeAttribute('hidden');
          qEl.classList.add('active');
        } else {
          qEl.setAttribute('hidden', '');
          qEl.classList.remove('active');
        }
      }

      // Disable finish button again
      if (finishBtn) {
        finishBtn.disabled = true;
        finishBtn.innerHTML = '<i class="bi bi-check-circle me-1"></i> Finish';
      }
    });
  }

  // ===== OPTION TABS (Options for Action section) =====
  document.querySelectorAll('[data-option-tab]').forEach(function (tab) {
    tab.addEventListener('click', function () {
      const i = parseInt(tab.getAttribute('data-option-tab'), 10);
      document.querySelectorAll('[data-option-tab]').forEach(function (t, idx) {
        const on = idx === i;
        t.classList.toggle('active', on);
        t.setAttribute('aria-selected', on ? 'true' : 'false');
      });
      document.querySelectorAll('.option-content-pane').forEach(function (pane, idx) {
        if (idx === i) {
          pane.classList.add('active');
          pane.removeAttribute('hidden');
        } else {
          pane.classList.remove('active');
          pane.setAttribute('hidden', '');
        }
      });
    });
  });

  // ===== LEARN MORE TOGGLES =====
  document.querySelectorAll('.learn-more-toggle').forEach(function (btn) {
    btn.addEventListener('click', function () {
      const id = btn.getAttribute('aria-controls');
      const panel = id ? document.getElementById(id) : null;
      if (!panel) return;
      const open = panel.classList.toggle('open');
      btn.setAttribute('aria-expanded', open ? 'true' : 'false');
      const icon = btn.querySelector('.learn-more-toggle-icon');
      if (icon) icon.textContent = open ? '−' : '+';
    });
  });

  // ===== INIT =====
  updateProgress();
  updateNavLinks();
  updateNavButtons();

  // Make headings focusable for a11y section announcements
  sections.forEach(section => {
    const heading = section.querySelector('h1, h2');
    if (heading) heading.setAttribute('tabindex', '-1');
  });

})();
